server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.mvc2.domain
  configLocation: classpath:mybatis/mybatis-config.xml
#showSql
logging:
  level:
    com.example.demo.mapper: debug